#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I/usr/include/freetype2 -Isource/extern/include
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -ldl -lglfw -lm -lfreetype

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -Wall -ggdb3
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/RenderToTexture

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/RenderToTexture

OBJ_DEBUG = $(OBJDIR_DEBUG)/source/kernel/error_handler.o $(OBJDIR_DEBUG)/source/kernel/kernel.o $(OBJDIR_DEBUG)/source/kernel/window_events.o $(OBJDIR_DEBUG)/source/main.o $(OBJDIR_DEBUG)/source/math/matrix.o $(OBJDIR_DEBUG)/source/mir/mir.o $(OBJDIR_DEBUG)/source/mir/team.o $(OBJDIR_DEBUG)/source/mir/tile.o $(OBJDIR_DEBUG)/source/mir/unit.o $(OBJDIR_DEBUG)/source/utils/utils.o $(OBJDIR_DEBUG)/source/graphics/shaders.o $(OBJDIR_DEBUG)/source/extern/src/glad.o $(OBJDIR_DEBUG)/source/graphics/camera.o $(OBJDIR_DEBUG)/source/graphics/font.o $(OBJDIR_DEBUG)/source/graphics/graphics.o $(OBJDIR_DEBUG)/source/graphics/textures.o $(OBJDIR_DEBUG)/source/gui/button.o $(OBJDIR_DEBUG)/source/gui/gui.o $(OBJDIR_DEBUG)/source/gui/label.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/source/kernel/error_handler.o $(OBJDIR_RELEASE)/source/kernel/kernel.o $(OBJDIR_RELEASE)/source/kernel/window_events.o $(OBJDIR_RELEASE)/source/main.o $(OBJDIR_RELEASE)/source/math/matrix.o $(OBJDIR_RELEASE)/source/mir/mir.o $(OBJDIR_RELEASE)/source/mir/team.o $(OBJDIR_RELEASE)/source/mir/tile.o $(OBJDIR_RELEASE)/source/mir/unit.o $(OBJDIR_RELEASE)/source/utils/utils.o $(OBJDIR_RELEASE)/source/graphics/shaders.o $(OBJDIR_RELEASE)/source/extern/src/glad.o $(OBJDIR_RELEASE)/source/graphics/camera.o $(OBJDIR_RELEASE)/source/graphics/font.o $(OBJDIR_RELEASE)/source/graphics/graphics.o $(OBJDIR_RELEASE)/source/graphics/textures.o $(OBJDIR_RELEASE)/source/gui/button.o $(OBJDIR_RELEASE)/source/gui/gui.o $(OBJDIR_RELEASE)/source/gui/label.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/source/kernel || mkdir -p $(OBJDIR_DEBUG)/source/kernel
	test -d $(OBJDIR_DEBUG)/source || mkdir -p $(OBJDIR_DEBUG)/source
	test -d $(OBJDIR_DEBUG)/source/math || mkdir -p $(OBJDIR_DEBUG)/source/math
	test -d $(OBJDIR_DEBUG)/source/mir || mkdir -p $(OBJDIR_DEBUG)/source/mir
	test -d $(OBJDIR_DEBUG)/source/utils || mkdir -p $(OBJDIR_DEBUG)/source/utils
	test -d $(OBJDIR_DEBUG)/source/graphics || mkdir -p $(OBJDIR_DEBUG)/source/graphics
	test -d $(OBJDIR_DEBUG)/source/extern/src || mkdir -p $(OBJDIR_DEBUG)/source/extern/src
	test -d $(OBJDIR_DEBUG)/source/gui || mkdir -p $(OBJDIR_DEBUG)/source/gui

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/source/kernel/error_handler.o: source/kernel/error_handler.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/kernel/error_handler.c -o $(OBJDIR_DEBUG)/source/kernel/error_handler.o

$(OBJDIR_DEBUG)/source/kernel/kernel.o: source/kernel/kernel.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/kernel/kernel.c -o $(OBJDIR_DEBUG)/source/kernel/kernel.o

$(OBJDIR_DEBUG)/source/kernel/window_events.o: source/kernel/window_events.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/kernel/window_events.c -o $(OBJDIR_DEBUG)/source/kernel/window_events.o

$(OBJDIR_DEBUG)/source/main.o: source/main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/main.c -o $(OBJDIR_DEBUG)/source/main.o

$(OBJDIR_DEBUG)/source/math/matrix.o: source/math/matrix.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/math/matrix.c -o $(OBJDIR_DEBUG)/source/math/matrix.o

$(OBJDIR_DEBUG)/source/mir/mir.o: source/mir/mir.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/mir/mir.c -o $(OBJDIR_DEBUG)/source/mir/mir.o

$(OBJDIR_DEBUG)/source/mir/team.o: source/mir/team.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/mir/team.c -o $(OBJDIR_DEBUG)/source/mir/team.o

$(OBJDIR_DEBUG)/source/mir/tile.o: source/mir/tile.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/mir/tile.c -o $(OBJDIR_DEBUG)/source/mir/tile.o

$(OBJDIR_DEBUG)/source/mir/unit.o: source/mir/unit.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/mir/unit.c -o $(OBJDIR_DEBUG)/source/mir/unit.o

$(OBJDIR_DEBUG)/source/utils/utils.o: source/utils/utils.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/utils/utils.c -o $(OBJDIR_DEBUG)/source/utils/utils.o

$(OBJDIR_DEBUG)/source/graphics/shaders.o: source/graphics/shaders.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/graphics/shaders.c -o $(OBJDIR_DEBUG)/source/graphics/shaders.o

$(OBJDIR_DEBUG)/source/extern/src/glad.o: source/extern/src/glad.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/extern/src/glad.c -o $(OBJDIR_DEBUG)/source/extern/src/glad.o

$(OBJDIR_DEBUG)/source/graphics/camera.o: source/graphics/camera.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/graphics/camera.c -o $(OBJDIR_DEBUG)/source/graphics/camera.o

$(OBJDIR_DEBUG)/source/graphics/font.o: source/graphics/font.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/graphics/font.c -o $(OBJDIR_DEBUG)/source/graphics/font.o

$(OBJDIR_DEBUG)/source/graphics/graphics.o: source/graphics/graphics.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/graphics/graphics.c -o $(OBJDIR_DEBUG)/source/graphics/graphics.o

$(OBJDIR_DEBUG)/source/graphics/textures.o: source/graphics/textures.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/graphics/textures.c -o $(OBJDIR_DEBUG)/source/graphics/textures.o

$(OBJDIR_DEBUG)/source/gui/button.o: source/gui/button.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/gui/button.c -o $(OBJDIR_DEBUG)/source/gui/button.o

$(OBJDIR_DEBUG)/source/gui/gui.o: source/gui/gui.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/gui/gui.c -o $(OBJDIR_DEBUG)/source/gui/gui.o

$(OBJDIR_DEBUG)/source/gui/label.o: source/gui/label.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source/gui/label.c -o $(OBJDIR_DEBUG)/source/gui/label.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/source/kernel
	rm -rf $(OBJDIR_DEBUG)/source
	rm -rf $(OBJDIR_DEBUG)/source/math
	rm -rf $(OBJDIR_DEBUG)/source/mir
	rm -rf $(OBJDIR_DEBUG)/source/utils
	rm -rf $(OBJDIR_DEBUG)/source/graphics
	rm -rf $(OBJDIR_DEBUG)/source/extern/src
	rm -rf $(OBJDIR_DEBUG)/source/gui

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/source/kernel || mkdir -p $(OBJDIR_RELEASE)/source/kernel
	test -d $(OBJDIR_RELEASE)/source || mkdir -p $(OBJDIR_RELEASE)/source
	test -d $(OBJDIR_RELEASE)/source/math || mkdir -p $(OBJDIR_RELEASE)/source/math
	test -d $(OBJDIR_RELEASE)/source/mir || mkdir -p $(OBJDIR_RELEASE)/source/mir
	test -d $(OBJDIR_RELEASE)/source/utils || mkdir -p $(OBJDIR_RELEASE)/source/utils
	test -d $(OBJDIR_RELEASE)/source/graphics || mkdir -p $(OBJDIR_RELEASE)/source/graphics
	test -d $(OBJDIR_RELEASE)/source/extern/src || mkdir -p $(OBJDIR_RELEASE)/source/extern/src
	test -d $(OBJDIR_RELEASE)/source/gui || mkdir -p $(OBJDIR_RELEASE)/source/gui

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/source/kernel/error_handler.o: source/kernel/error_handler.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/kernel/error_handler.c -o $(OBJDIR_RELEASE)/source/kernel/error_handler.o

$(OBJDIR_RELEASE)/source/kernel/kernel.o: source/kernel/kernel.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/kernel/kernel.c -o $(OBJDIR_RELEASE)/source/kernel/kernel.o

$(OBJDIR_RELEASE)/source/kernel/window_events.o: source/kernel/window_events.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/kernel/window_events.c -o $(OBJDIR_RELEASE)/source/kernel/window_events.o

$(OBJDIR_RELEASE)/source/main.o: source/main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/main.c -o $(OBJDIR_RELEASE)/source/main.o

$(OBJDIR_RELEASE)/source/math/matrix.o: source/math/matrix.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/math/matrix.c -o $(OBJDIR_RELEASE)/source/math/matrix.o

$(OBJDIR_RELEASE)/source/mir/mir.o: source/mir/mir.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/mir/mir.c -o $(OBJDIR_RELEASE)/source/mir/mir.o

$(OBJDIR_RELEASE)/source/mir/team.o: source/mir/team.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/mir/team.c -o $(OBJDIR_RELEASE)/source/mir/team.o

$(OBJDIR_RELEASE)/source/mir/tile.o: source/mir/tile.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/mir/tile.c -o $(OBJDIR_RELEASE)/source/mir/tile.o

$(OBJDIR_RELEASE)/source/mir/unit.o: source/mir/unit.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/mir/unit.c -o $(OBJDIR_RELEASE)/source/mir/unit.o

$(OBJDIR_RELEASE)/source/utils/utils.o: source/utils/utils.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/utils/utils.c -o $(OBJDIR_RELEASE)/source/utils/utils.o

$(OBJDIR_RELEASE)/source/graphics/shaders.o: source/graphics/shaders.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/graphics/shaders.c -o $(OBJDIR_RELEASE)/source/graphics/shaders.o

$(OBJDIR_RELEASE)/source/extern/src/glad.o: source/extern/src/glad.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/extern/src/glad.c -o $(OBJDIR_RELEASE)/source/extern/src/glad.o

$(OBJDIR_RELEASE)/source/graphics/camera.o: source/graphics/camera.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/graphics/camera.c -o $(OBJDIR_RELEASE)/source/graphics/camera.o

$(OBJDIR_RELEASE)/source/graphics/font.o: source/graphics/font.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/graphics/font.c -o $(OBJDIR_RELEASE)/source/graphics/font.o

$(OBJDIR_RELEASE)/source/graphics/graphics.o: source/graphics/graphics.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/graphics/graphics.c -o $(OBJDIR_RELEASE)/source/graphics/graphics.o

$(OBJDIR_RELEASE)/source/graphics/textures.o: source/graphics/textures.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/graphics/textures.c -o $(OBJDIR_RELEASE)/source/graphics/textures.o

$(OBJDIR_RELEASE)/source/gui/button.o: source/gui/button.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/gui/button.c -o $(OBJDIR_RELEASE)/source/gui/button.o

$(OBJDIR_RELEASE)/source/gui/gui.o: source/gui/gui.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/gui/gui.c -o $(OBJDIR_RELEASE)/source/gui/gui.o

$(OBJDIR_RELEASE)/source/gui/label.o: source/gui/label.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source/gui/label.c -o $(OBJDIR_RELEASE)/source/gui/label.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/source/kernel
	rm -rf $(OBJDIR_RELEASE)/source
	rm -rf $(OBJDIR_RELEASE)/source/math
	rm -rf $(OBJDIR_RELEASE)/source/mir
	rm -rf $(OBJDIR_RELEASE)/source/utils
	rm -rf $(OBJDIR_RELEASE)/source/graphics
	rm -rf $(OBJDIR_RELEASE)/source/extern/src
	rm -rf $(OBJDIR_RELEASE)/source/gui

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

